# Generated by Django 4.2.7 on 2023-11-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantidade_de_aulas_semana', models.IntegerField()),
                ('aula_dividida', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('aulas_diarias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('disciplinas', models.ManyToManyField(related_name='disciplinas', to='schedule.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('disciplina', models.ManyToManyField(related_name='disciplina', to='schedule.disciplina')),
                ('disponibilidade', models.ManyToManyField(related_name='disponibilidade', to='schedule.weekday')),
                ('turmas', models.ManyToManyField(related_name='turmas', to='schedule.turma')),
            ],
        ),
    ]
